"""
Export: the GLB the site loads, and the anchors the camera path reads.

  room.glb
    baked_room / baked_desk / baked_lab   one mesh per atlas, unlit, atlas map
    crt_glass, screen_*, whiteboard_surface, led_*, tape_*   live objects
    hit_*                                  invisible pick volumes (extras: station, item)
  anchors.generated.ts                     anchor_* empties, in three.js coords

The atlases are written through the scene's view transform (AgX), so the
site shows exactly what the preview renders showed; the runtime draws them
without tone mapping.
"""
import json
import math
import os

import bpy

from bake import LIGHTMAP_UV

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..'))
ANCHORS_TS = os.path.join(REPO, 'src', 'scenes', 'room', 'anchors.generated.ts')


def three(v):
    """Blender (x, y, z-up) -> three.js (x, y-up, z-toward-viewer)."""
    return [round(v[0], 5), round(v[2], 5), round(-v[1], 5)]


# Exposure the atlases are developed at, like a camera exposing for a dark
# room: +1.3 EV through AgX, so highlights roll off instead of clipping.
EXPOSURE_EV = 1.3


def _save_atlas(img, path):
    scene = bpy.context.scene
    scene.view_settings.exposure = EXPOSURE_EV
    settings = scene.render.image_settings
    settings.file_format = 'PNG'
    settings.color_mode = 'RGB'
    settings.color_depth = '8'
    img.save_render(path, scene=scene)
    out = bpy.data.images.load(path)
    out.name = os.path.splitext(os.path.basename(path))[0]
    return out


def _unlit_atlas_material(name, image):
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    nt = mat.node_tree
    bsdf = nt.nodes['Principled BSDF']
    uv = nt.nodes.new('ShaderNodeUVMap')
    uv.uv_map = 'UVMap'
    tex = nt.nodes.new('ShaderNodeTexImage')
    tex.image = image
    nt.links.new(uv.outputs['UV'], tex.inputs['Vector'])
    nt.links.new(tex.outputs['Color'], bsdf.inputs['Base Color'])
    bsdf.inputs['Roughness'].default_value = 1.0
    return mat


def _finish_atlas(name, merged, image):
    """The merged atlas mesh keeps only its lightmap UV and one unlit
    material showing the baked atlas."""
    mesh = merged.data
    for uv in [u for u in mesh.uv_layers if u.name != LIGHTMAP_UV]:
        mesh.uv_layers.remove(uv)
    mesh.uv_layers[LIGHTMAP_UV].name = 'UVMap'
    mesh.materials.clear()
    mesh.materials.append(_unlit_atlas_material(f'atlas_{name}', image))


def _keep_live_uvs():
    carrier = bpy.data.images.new('uv_carrier', 4, 4, alpha=False)
    carrier.pixels = [1.0] * (4 * 4 * 4)
    carrier.pack()
    done = set()
    for o in bpy.data.collections['live'].all_objects:
        if o.type != 'MESH' or not o.data.uv_layers:
            continue
        for slot in o.material_slots:
            mat = slot.material
            if mat is None or mat.name in done or not mat.use_nodes:
                continue
            done.add(mat.name)
            nt = mat.node_tree
            bsdf = nt.nodes.get('Principled BSDF')
            if bsdf is None or bsdf.inputs['Base Color'].is_linked:
                continue
            uv = nt.nodes.new('ShaderNodeUVMap')
            uv.uv_map = 'UVMap'
            tex = nt.nodes.new('ShaderNodeTexImage')
            tex.image = carrier
            nt.links.new(uv.outputs['UV'], tex.inputs['Vector'])
            nt.links.new(tex.outputs['Color'], bsdf.inputs['Base Color'])


def _anchors():
    out = {}
    for o in bpy.data.objects:
        if not o.name.startswith('anchor_'):
            continue
        key = o.name[len('anchor_'):]
        entry = {'position': three(o.matrix_world.translation)}
        if 'look' in o:
            lx, ly, lz = o['look']
            entry['look'] = [round(lx, 5), round(ly, 5), round(lz, 5)]
        for k in ('width', 'height'):
            if k in o:
                entry[k] = round(float(o[k]), 5)
        out[key] = entry
    return out


def _write_anchors(anchors):
    body = json.dumps(anchors, indent=2, sort_keys=True)
    ts = (
        '/**\n'
        ' * GENERATED by art/room/export.py — do not edit. Rebuild with\n'
        ' * `npm run art:build`. Positions are three.js world coordinates (metres).\n'
        ' */\n'
        'export interface Anchor {\n'
        '  readonly position: readonly [number, number, number];\n'
        '  /** Unit vector the anchored surface faces. */\n'
        '  readonly look?: readonly [number, number, number];\n'
        '  readonly width?: number;\n'
        '  readonly height?: number;\n'
        '}\n\n'
        f'export const ANCHORS = {body} as const satisfies Record<string, Anchor>;\n'
    )
    with open(ANCHORS_TS, 'w') as f:
        f.write(ts)


def export(out_dir, atlases):
    os.makedirs(out_dir, exist_ok=True)
    for name, (img, merged) in atlases.items():
        png = _save_atlas(img, os.path.join(out_dir, f'atlas_{name}.png'))
        _finish_atlas(name, merged, png)

    # Live objects keep simple materials (the runtime replaces them); drop
    # the bake-target nodes so nothing stray is exported.
    for mat in bpy.data.materials:
        if mat.use_nodes and 'bake_target' in mat.node_tree.nodes:
            mat.node_tree.nodes.remove(mat.node_tree.nodes['bake_target'])

    # The glTF exporter drops a mesh's UVs when its material samples no
    # texture, and the live planes (screens, CRT glass, whiteboard, label
    # tapes) need theirs for the runtime canvases. A 4 px white image read
    # through UVMap keeps them.
    _keep_live_uvs()

    # Lights shaped the bake; the runtime has no use for them.
    for o in [o for o in bpy.data.objects if o.type == 'LIGHT']:
        bpy.data.objects.remove(o)

    bpy.ops.export_scene.gltf(
        filepath=os.path.join(out_dir, 'room.raw.glb'),
        export_format='GLB',
        export_extras=True,
        export_yup=True,
        export_apply=True,
        export_lights=False,
        export_cameras=False,
        export_animations=False,
        export_image_format='AUTO',
    )
    _write_anchors(_anchors())
    print(f'[export] wrote {out_dir}/room.raw.glb and {ANCHORS_TS}', flush=True)
