/**
 * GENERATED by art/room/export.py — do not edit. Rebuild with
 * `npm run art:build`. Positions are three.js world coordinates (metres).
 */
export interface Anchor {
  readonly position: readonly [number, number, number];
  /** Unit vector the anchored surface faces. */
  readonly look?: readonly [number, number, number];
  readonly width?: number;
  readonly height?: number;
}

export const ANCHORS = {
  "doorway": {
    "position": [
      1.55,
      1.55,
      1.75
    ]
  },
  "floppies": {
    "height": 0.35,
    "look": [
      1,
      0,
      0
    ],
    "position": [
      -1.74,
      1.339,
      -0.81
    ],
    "width": 0.34
  },
  "floppy_row0": {
    "look": [
      1,
      0,
      0
    ],
    "position": [
      -1.85,
      1.219,
      -0.81
    ]
  },
  "floppy_row1": {
    "look": [
      1,
      0,
      0
    ],
    "position": [
      -1.95,
      1.279,
      -0.81
    ]
  },
  "laptop": {
    "height": 0.212,
    "look": [
      0.57543,
      0.13862,
      0.80602
    ],
    "position": [
      -1.21339,
      1.02163,
      -1.7428
    ],
    "width": 0.334
  },
  "monitor_big": {
    "height": 0.39848,
    "look": [
      -0.31457,
      0.0,
      0.94924
    ],
    "position": [
      0.23685,
      1.14924,
      -1.75051
    ],
    "width": 0.70842
  },
  "monitor_mid": {
    "height": 0.33622,
    "look": [
      -0.07991,
      0.0,
      0.9968
    ],
    "position": [
      -0.6208,
      1.11811,
      -1.79003
    ],
    "width": 0.59773
  },
  "rack": {
    "height": 0.71,
    "look": [
      1,
      0,
      0
    ],
    "position": [
      -1.48,
      0.355,
      -0.9
    ],
    "width": 0.84
  },
  "room_max": {
    "position": [
      2.3,
      2.5,
      2.4
    ]
  },
  "room_min": {
    "position": [
      -2.0,
      0.0,
      -2.0
    ]
  },
  "screen": {
    "height": 0.19,
    "look": [
      1.0,
      0.0,
      0.0
    ],
    "position": [
      -1.41437,
      0.955,
      -1.12
    ],
    "width": 0.25
  },
  "whiteboard": {
    "height": 0.6,
    "look": [
      1,
      0,
      0
    ],
    "position": [
      -1.976,
      1.6,
      -0.05
    ],
    "width": 1.0
  }
} as const satisfies Record<string, Anchor>;
